---
title: "task1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(splines2)
library(plyr)
library(readr)
library(dplyr)
library(caret)
library(tensor)
```
one-hot encoding
```{r}
dmy <- dummyVars(" ~ .", data = dat, fullRank = T)
dat_transformed <- data.frame(predict(dmy, newdata = dat))

glimpse(dat_transformed)
```

```{r}
#large dataframe with 2 continuous variable and 1 categorical variables
lcol1 = rnorm(100,0,1)
lcol2 = rnorm(100,0,1)
lcol3 = factor(rbinom(100,3,.4))
lcol4 = factor(rbinom(100,5,.5))
lcol5 = rnorm(100,0,1)
largeds = data.frame(lcol1,lcol2,lcol3,lcol4,lcol5)

#small dataframe with 2 continuous variable and 1 categorical variables
scol1 = rnorm(10,0,1)
scol2 = rnorm(10,0,1)
scol3 = factor(rbinom(100,3,.4))
scol4 = factor(rbinom(100,5,.3))
smallds = data.frame(scol1,scol2,scol3,scol4)
```

```{r}

```
function
```{r}
basis <- function(data, basis='poly', degree=NULL, returnBasis='product') {
  #separating numerical and categorical variables into two different dataframes
  cols = unlist(lapply(data,is.numeric))
  n_data = data[, cols]
  temp_c_data = data[, !cols]
  #one hot encoding
  dmy <- dummyVars(" ~ .", data = temp_c_data, fullRank = T)
  c_data <- data.frame(predict(dmy, newdata = temp_c_data))
  #basis selection
  if (basis == 'bspline') {
    if(returnBasis == 'product') {
      nBasis = NULL
      nTensor = bSpline(unlist(n_data[1]), intercept = TRUE) 
      for(i in seq(from=2, to=ncol(n_data), by=1)){
        tempNBasis = bSpline(unlist(n_data[i]), intercept = TRUE) 
        for(j in seq(from=1, to=ncol(nTensor))){
          for(k in seq(from=1, to=ncol(tempNBasis), by=1)){
            nBasis = cbind(nTensor, nTensor[,j]*tempNBasis[,k])
          }
        }
      }
      cBasis = NULL
      cTensor = bSpline(unlist(c_data[1]), intercept = TRUE) 
      for(i in seq(from=2, to=ncol(c_data), by=1)){
        tempCBasis = bSpline(unlist(c_data[i]), intercept = TRUE) 
        for(j in seq(from=1, to=ncol(cTensor))){
          for(k in seq(from=1, to=ncol(tempCBasis), by=1)){
            cBasis = cbind(cTensor, cTensor[,j]*tempCBasis[,k])
          }
        }
      }
      return(nBasis*cBasis)
    } else if(returnBasis  ==' additive') {
      nBasis = NULL
      for(i in seq(from=1, to=ncol(n_data), by=1)){
        nBasis = rbind(nBasis, bSpline(unlist(n_data[i]), intercept = TRUE))
      }
      cBasis = NULL
      for(i in seq(from=1, to=ncol(c_data), by=1)){
        cBasis = rbind(cBasis, bSpline(unlist(c_data[i]), intercept = TRUE) )
      }
      return(nBasis*cBasis)
    }
  
  } else if(basis=='poly'){
    basis <- poly(dat_transformed, degree = degree + 1)
    return(basis)
  }
}
```

```{r}
#tests
blarge = basis(largeds, 'bspline', returnBasis='additive')



```
for bspline, find bspline of each column and find tensor product tX`
for categorical, one hot encoding and find the basis matrix
combine both one hot encoding matrix and basis matrices

in basis function provide option to pick tensor or additive basis
